services:
  python:
    image: python-playground:3.9
    container_name: python
    build: .
    working_dir: /app
    environment:
      - PYTHONDONTWRITEBYTECODE=1 # __pycache__が生成されなくなる
    volumes:
      - .:/app
    tty: true
